pimcore_data_hub:
    configurations:
        AirportRunawayImporter:
            general:
                type: dataImporterDataObject
                name: AirportRunawayImporter
                description: ''
                group: ''
                active: false
                path: null
                modificationDate: 1740930704
                createDate: 1740758240
            loaderConfig:
                type: asset
                settings:
                    assetPath: /public/var/assets/runways_lm_short.csv
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '4'
                loadingStrategy:
                    type: notLoad
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: noChangeUnpublishNew
            processingConfig:
                executionType: parallel
                idDataIndex: ''
            mappingConfig:
                -
                    label: airport_identifier
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: airport_identifier
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: length
                    dataSourceIndex:
                        - '3'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: length
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: width
                    dataSourceIndex:
                        - '4'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: width
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: surface
                    dataSourceIndex:
                        - '5'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: surface
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: lighted
                    dataSourceIndex:
                        - '6'
                    transformationResultType: boolean
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: lighted
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: boolean
                -
                    label: closed
                    dataSourceIndex:
                        - '7'
                    transformationResultType: boolean
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: closed
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: boolean
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
